## NumPy

### Importing Required Libraries


In [2]:
! pip install numpy # Check this library is installed or not ?

In [3]:
import numpy

In [7]:
import numpy as np  # Import NumPy for array manipulations
import time  # Import Time for performance measurement

In [6]:
print(np.__version__)

1.26.4


### Creating Arrays


In [9]:
# 0_D Arrays: 

arr = np.array(50)

print(arr)

50


In [12]:
# 1_D Arrays: 

arr = np.array([1, 2, 3, 4, 5])  # Creating a 1D NumPy array

print(arr)  # Output: [1 2 3 4 5]

print(type(arr))  # Output: <class 'numpy.ndarray'>




[1 2 3 4 5]
<class 'numpy.ndarray'>


In [25]:
# 2_D Arrays: 
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]

Arrays = np.array([list1, list2])  # Creating a 2D NumPy array

print(Arrays)

print(Arrays.ndim)  # Output: 2 (for 2D array)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [19]:
# 3D Arrays:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]
list3 = [10, 11, 12, 13, 14]  # Adjusted to match the shape of list1 and list2

# Creating a 3D NumPy array
Arrays = np.array([[list1], [list2], [list3]])  # Nested lists to form a 3D array

print(Arrays)

print(Arrays.ndim)  # Output: 3 (for 3D array)


[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[10 11 12 13 14]]]
3


### Array Properties

In [24]:
my_arr = np.array([10, 20, 30, 40, 50])

print(my_arr.ndim)  # Output: 1 (dimension)

print(my_arr.size)  # Output: 5 (number of elements)

print(my_arr.shape)  # Output: (5,) (shape of the array)

print(my_arr.dtype)  # Output: int64 (data type)

print(my_arr.itemsize)  # Output: 8 (size of each element in bytes)

print(my_arr.nbytes)  # Output: 40 (total memory usage)

1
5
(5,)
int32
4
20


In [32]:
array_2 = np.array([list1, list2])

print(array_2.ndim)

print(array_2.size)

print(array_2.shape)

print(array_2.dtype)

print(array_2.itemsize)

print(array_2.nbytes)


2
10
(2, 5)
int32
4
40


In [37]:
array_3 = np.array([[list1], [list2], [list3]])

print(array_3.ndim)

print(array_3.shape)

print(array_3.size)

print(array_3.dtype)

print(array_3.itemsize)

print(array_3.nbytes)


3
(3, 1, 5)
15
int32
4
60


### Array Description Function

In [39]:
ar = np.array(list1)

In [51]:
def describe(ar):
    print(f"Print Array: {ar}")
    print(f"Dimensions: {ar.ndim}")
    print(f"Shape: {ar.shape}")
    print(f"Size: {ar.size}")
    print(f"Data type: {ar.dtype}")

describe(ar)


Print Array: [1 2 3 4 5]
Dimensions: 1
Shape: (5,)
Size: 5
Data type: int32


### Various Array Creations


In [52]:
# Array Of Ones:

arr2 = np.ones((2, 2))

print(arr2)

[[1. 1.]
 [1. 1.]]


In [53]:
describe(arr2)

Print Array: [[1. 1.]
 [1. 1.]]
Dimensions: 2
Shape: (2, 2)
Size: 4
Data type: float64


In [54]:
# Array Of Zeros 
arr3 = np.zeros((3, 4))
describe(arr3)


Print Array: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Dimensions: 2
Shape: (3, 4)
Size: 12
Data type: float64


In [55]:
arr4 = np.full((2, 2), 10)

describe(arr4)

Print Array: [[10 10]
 [10 10]]
Dimensions: 2
Shape: (2, 2)
Size: 4
Data type: int32


In [57]:
# Identity matrix
arr5 = np.eye(3)
describe(arr5)

Print Array: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Dimensions: 2
Shape: (3, 3)
Size: 9
Data type: float64


In [56]:
# Range of values
arr6 = np.arange(10)
describe(arr6)

Print Array: [0 1 2 3 4 5 6 7 8 9]
Dimensions: 1
Shape: (10,)
Size: 10
Data type: int32


In [58]:
# Evenly spaced values
arr7 = np.linspace(0, 1, 5)
describe(arr7)

Print Array: [0.   0.25 0.5  0.75 1.  ]
Dimensions: 1
Shape: (5,)
Size: 5
Data type: float64


In [59]:
# Random values
arr8 = np.random.rand(3, 3)
describe(arr8)

Print Array: [[0.49814275 0.73621672 0.54372855]
 [0.05460469 0.15714315 0.65085423]
 [0.9828584  0.82067049 0.02280855]]
Dimensions: 2
Shape: (3, 3)
Size: 9
Data type: float64


In [60]:
# Random integers
arr9 = np.random.randint(0, 10, (3, 3))
describe(arr9)


Print Array: [[7 4 6]
 [1 8 8]
 [5 5 7]]
Dimensions: 2
Shape: (3, 3)
Size: 9
Data type: int32


In [61]:
# Reshaping an array
arr10 = arr3.reshape(12)
describe(arr10)

Print Array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Dimensions: 1
Shape: (12,)
Size: 12
Data type: float64


In [62]:
# Array with same shape and type as another array
arr11 = np.ones_like(arr10)
describe(arr11)

Print Array: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Dimensions: 1
Shape: (12,)
Size: 12
Data type: float64


### Array Operations

In [71]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

In [66]:
print('a + b :', a + b) # Element-wise addition

a + b : [ 7  9 11 13 15]


In [72]:
print('a - b :', a - b) # Element-wise subtraction

a - b : [-5 -5 -5 -5 -5]


In [73]:
print('a * b :', a * b) # Element-wise multiplication

a * b : [ 6 14 24 36 50]


In [74]:
print('a / b :', a / b) # Element-wise dividion

a / b : [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [70]:
print('a % b :', a % b) # Element-wise modulo

a % b : [1 2 3 4 5]


In [111]:
angle_in_radians = np.radians(90)

print("Sin(90°):", np.sin(angle_in_radians))  # Sin of 90 degrees
print("Cos(90°):", np.cos(angle_in_radians))  # Cos of 90 degrees
print("Tan(90°):", np.tan(angle_in_radians))  # Tan of 90 degrees

Sin(90°): 1.0
Cos(90°): 6.123233995736766e-17
Tan(90°): 1.633123935319537e+16


In [118]:
# Exponential of 10 (e^10)
print("Exp(10):", np.exp(10))

# Natural logarithm of 10 (log base e)
print("Log(10):", np.log(10))

# Base-10 logarithm of 10
print("Log10(10):", np.log10(10))

Exp(10): 22026.465794806718
Log(10): 2.302585092994046
Log10(10): 1.0


In [125]:
# Print the value of pi (π)
print("Pi (π):", np.pi)

# Print the value of Euler's number (e)
print("Euler's number (e):", np.e)

# Print positive infinity
print("Infinity (∞):", np.inf)

# Print NaN (Not a Number)
print("NaN:", np.nan)

Pi (π): 3.141592653589793
Euler's number (e): 2.718281828459045
Infinity (∞): inf
NaN: nan


### Scalar Operations


In [76]:
arr_1 = np.array([1, 2, 3, 4, 5])

arr_2 = np.array([10, 20, 30, 40, 50])

In [80]:
print(f"a + 10 : {arr_1 + 10}")


a + 10 : [11 12 13 14 15]


In [79]:
print(f"a * 10 : {arr_1 * 10}")


a * 10 : [10 20 30 40 50]


In [82]:
print(f"b / 10 : {arr_2 // 10}")


b / 10 : [1 2 3 4 5]


In [83]:
print(f"b - 10 : {arr_2 - 10}")


b - 10 : [ 0 10 20 30 40]


In [86]:
print(f"a % b : {arr_1 % arr_2}")


a % b : [1 2 3 4 5]


### Dot Product

In [89]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

In [90]:
print(f"a.b : {a.dot(b)}")

a.b : 130


In [92]:
c = np.array([[1], [2], [3], [4], [5]])
print('a.c:', a.dot(c))

a.c: [55]


### Array Statistics

In [93]:
Arr = np.array([1, 2, 3, 4, 5])

In [95]:
print('Min:', Arr.min()) # Minimum value in the array


Min: 1


In [97]:
print('Max:', Arr.max()) # Maximum value in the array


Max: 5


In [98]:
print('Sum:', Arr.sum()) # Sum of all elements in the array

Sum: 15


In [ ]:
print('Mean:', Arr.mean()) # Mean (average) of the array elements

In [ ]:
print('Std Dev:', Arr.std()) # Standard deviation of the array elements


In [100]:
print('Variance:', Arr.var()) # Variance of the array elements

Variance: 2.0


### Matrix Multiplication

In [105]:
a = np.array([[3, 1], [1, 3]])
b = np.array([[3, 5], [4, 2]])

z = np.dot(a, b)  # Matrix multiplication
print(f'Dot Two Arrays: \n{z}')

Dot Two Arrays: 
[[13 17]
 [15 11]]


In [107]:
# Element-wise addition, subtraction, division, etc.
print(f'ADD Two Arrays : \n{np.add(a, b)}')

print(f'Sub Two Arrays : \n{np.subtract(a, b)}')

print(f'Multiply Two Arrays : \n{np.multiply(a, b)}')

print(f'Divide Two Arrays : \n{np.divide(a, b)}')

ADD Two Arrays : 
[[6 6]
 [5 5]]
Sub Two Arrays : 
[[ 0 -4]
 [-3  1]]
Multiply Two Arrays : 
[[9 5]
 [4 6]]
Divide Two Arrays : 
[[1.   0.2 ]
 [0.25 1.5 ]]


In [120]:
# Define a square matrix
a = np.array([[1, 2], [3, 4]])

# Compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(a)

print("Matrix A:")
print(a)
print("Eigenvalues of A:")
print(eigenvalues)
print("Eigenvectors of A:")
print(eigenvectors)

Matrix A:
[[1 2]
 [3 4]]
Eigenvalues of A:
[-0.37228132  5.37228132]
Eigenvectors of A:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### Performance Comparison: Loops vs Vectorized Operations python

In [108]:
a = np.arange(10000000)

# Using loops
start_time = time.time()
b = 0
for i in a:
    b += i
print(f'Sum using loop:\n{b}\nTime: {time.time()-start_time}')

# Using vectorized implementation
start_time = time.time()
print(f'Sum using vectorized implementation:\n{a.sum()}\nTime: {time.time()-start_time}')


C:\Users\CS\AppData\Local\Temp\ipykernel_15472\3575668372.py:7: RuntimeWarning: overflow encountered in scalar add
  b += i


Sum using loop:
-2014260032
Time: 1.5276365280151367
Sum using vectorized implementation:
-2014260032
Time: 0.0015065670013427734
